#!/bin/sh

pgrep -x sxhkd > /dev/null | sxhkd &
feh --bg-fill ~/Pictures/Wallpapers/himalaya.jpeg
sh ~/.config/polybar/launch.sh

# picom --backend xrender &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 5 
bspc config window_gap 0
bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

